import { useEffect, useState } from 'react';
import './evidence.css';

type Request = <T>(path: string, init?: RequestInit, token?: string | null) => Promise<T>;
type Archive = { id: string; status: string; transactionId: string | null; contentHash: string; error: string | null };
type Case = { id: string; offerId: string; title: string; status: string; payer: string | null; payee: string | null; jobId: string | null; coverage: string; updatedAt: string; payment: { status: string; rail: string | null }; archives: Archive[] };
type Record = { id: string; room: string; generation: number | null; message: { seq: number; ts: string; from: string; text: string; sig: string; nonce: string }; protocolValid: boolean; reason: string | null };
type Detail = Omit<Case, 'coverage'> & { records: Record[]; coverage: { status: string; gaps: unknown[]; notice: string }; source: { dealRoom: string | null }; assessment: { state: { offer?: { amount: string; asset: string; lock: string }; railRef?: string } | null; protocolValid: boolean; rejected: { reason: string }[]; payment: { status: string; rail: string | null; reason: string } }; attachments: { label: string; sha256: string }[] };
type Payload = { cases: Case[]; total: number; collector: { enabled: boolean; lastSyncAt: string | null; lastError: string | null; count: number; cases: number; archived: number; maxRecords: number } };
type Settings = { enabled: boolean; freeUploads: boolean; autoArchive: boolean; includePaper: boolean; maxUploadsPerDay: number; reportAgentId: string | null };
const short = (x?: string | null) => x ? `${x.slice(0, 14)}…${x.slice(-8)}` : 'Not observed';
const phase: { [key: string]: string } = { proposed: 'Offer observed', accepted: 'Two-party handshake', locked: 'Lock announced', claimed: 'Reveal observed', refunded: 'Refund announced', cancelled: 'Cancelled', incomplete: 'Incomplete' };
const roomLink = (room: string, seq?: number) => `https://technocore.chat/humans#r/${encodeURIComponent(room)}${seq === undefined ? '' : `/${seq}`}`;
function download(value: unknown, name: string) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export function Evidence({ request, token, agents }: { request: Request; token: string | null; agents: { id: string; did: string }[] }) {
  const [query, setQuery] = useState(''), [search, setSearch] = useState(''), [filter, setFilter] = useState('contracts'), [offset, setOffset] = useState(0);
  const [payload, setPayload] = useState<Payload | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [id, setId] = useState(() => location.hash.startsWith('#evidence/') ? decodeURIComponent(location.hash.slice(10)) : '');
  const [detail, setDetail] = useState<Detail | null>(null), [settings, setSettings] = useState<Settings | null>(null), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  const [permanent, setPermanent] = useState(false), [roomConsent, setRoomConsent] = useState(false);
  const [verification, setVerification] = useState<{ verdict: string; hashMatches: boolean; signaturesValid: boolean; attachmentsValid: boolean; notice: string } | null>(null);
  useEffect(() => { const update = () => setId(location.hash.startsWith('#evidence/') ? decodeURIComponent(location.hash.slice(10)) : ''); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  useEffect(() => { let active = true; const controller = new AbortController(); const load = async () => {
    try { const data = await request<Payload>(`/v1/evidence?q=${encodeURIComponent(search)}&status=${filter}&offset=${offset}`, { signal: controller.signal }); if (active) { setPayload(data); setError(''); } }
    catch (e) { if (active) setError(`Evidence unavailable: ${e instanceof Error ? e.message : 'request failed'}. Existing work remains in the Work board.`); }
  }; void load(); const timer = setInterval(() => void load(), 30000); return () => { active = false; controller.abort(); clearInterval(timer); }; }, [request, search, filter, offset, revision]);
  useEffect(() => { let active = true; const controller = new AbortController(); setDetail(null); if (id) void request<Detail>(`/v1/evidence/${encodeURIComponent(id)}`, { signal: controller.signal }).then(x => { if (active) setDetail(x); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; controller.abort(); }; }, [id, request, revision]);
  useEffect(() => { setSettings(null); setPermanent(false); setRoomConsent(false); }, [token]);
  async function act(fn: () => Promise<void>) { if (busy) return; setBusy(true); setNotice(''); try { await fn(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(false); } }
  function select(value: string) { location.hash = value ? `evidence/${value}` : 'evidence'; setId(value); }
  async function verify(file: File) { if (file.size > 200000) throw new Error('Use a bundle under 200 KB, or verify larger exports with the offline CLI.'); const b = JSON.parse(await file.text()); setVerification(await request('/v1/evidence/verify', { method: 'POST', body: JSON.stringify(b) })); }

  return <section className="evidence-view" aria-label="Evidence archive">
    <header className="evidence-heading"><div><span className="section-kicker">PACT / EVIDENCE REGISTER</span><h2>Agreements fade.<br />Keep the record.</h2><p>Find signed tclk offers and their observed deal history. Preserve the original records—not an AI retelling.</p></div><a className="evidence-source" href={roomLink('tclk-offers')} target="_blank" rel="noopener noreferrer">Source: tclk-offers ↗</a></header>
    <div className="evidence-metrics"><div><b>{payload?.collector.cases ?? '—'}</b><span>handshakes observed</span></div><div><b>{payload?.collector.archived ?? '—'}</b><span>archives retrieved</span></div><div><b>0</b><span>model calls for collection</span></div></div>
    <p className="evidence-boundary">A valid signature identifies a key. It does not prove work quality, payment, or a dispute verdict. Paper / memory rails carry no value.</p>
    <form className="evidence-search" onSubmit={e => { e.preventDefault(); setSearch(query.trim()); setOffset(0); }}><label><span>FIND A RECORD</span><input value={query} maxLength={180} onChange={e => setQuery(e.target.value)} placeholder="DID, contract, room, job ID, sequence or hash" /></label><button type="submit">Search →</button><label><span>SHOW</span><select value={filter} onChange={e => { setFilter(e.target.value); setOffset(0); }}><option value="contracts">Two-party deals</option><option value="all">Deals + offers</option><option value="claimed">Reveal observed</option><option value="locked">Lock announced</option><option value="refunded">Refund announced</option></select></label></form>
    <div className="evidence-tools"><label className="evidence-file">Recheck a JSON bundle<input type="file" accept=".json,application/json" disabled={busy} onChange={e => { const f = e.target.files?.[0]; if (f) void act(() => verify(f)); e.target.value = ''; }} /></label><button onClick={() => setRevision(x => x + 1)}>Refresh</button>{token && <button disabled={busy} onClick={() => void act(async () => { const p = await request<{ settings: Settings }>('/v1/evidence/settings', {}, token); setSettings(p.settings); })}>Operator settings</button>}</div>
    {verification && <div className="evidence-alert" role="status"><strong>{verification.verdict.replaceAll('_', ' ')}</strong><p>Bundle hash: {verification.hashMatches ? 'matches' : 'mismatch'} · Signatures: {verification.signaturesValid ? 'valid' : 'invalid'} · Attachments: {verification.attachmentsValid ? 'match' : 'invalid'}</p><p>{verification.notice} Rechecked by this runtime; independent offline verification is available in the repository.</p></div>}
    {notice && <p className="evidence-alert" role="status">{notice}</p>}{error && <p className="evidence-alert" role="alert">{error}</p>}
    {settings && <form className="evidence-settings" onSubmit={e => { e.preventDefault(); void act(async () => { const p = await request<{ settings: Settings }>('/v1/evidence/settings', { method: 'PATCH', body: JSON.stringify({ ...settings, confirmPermanent: permanent, confirmRoomPosting: roomConsent }) }, token); setSettings(p.settings); setNotice('Settings saved. No wallet or paid upload is enabled.'); setRevision(x => x + 1); }); }}>
      <h3>Collection & preservation</h3><p>Operator-only. Existing agents, API keys and task policies are unchanged.</p>
      {(['enabled','freeUploads','autoArchive','includePaper'] as const).map((key, n) => <label className="evidence-check" key={key}><input type="checkbox" checked={settings[key]} onChange={e => setSettings({ ...settings, [key]: e.target.checked })} />{['Read public tclk offers and derived deal rooms','Allow free-only Turbo uploads (under 100 KiB)','Automatically archive observed terminal deals with no known gaps','Include paper / memory rehearsals in automatic archives'][n]}</label>)}
      <label>Maximum upload attempts per UTC day<input type="number" min="1" max="10" value={settings.maxUploadsPerDay} onChange={e => setSettings({ ...settings, maxUploadsPerDay: Number(e.target.value) })} /></label>
      <label>Daily archive summary agent<select value={settings.reportAgentId ?? ''} onChange={e => setSettings({ ...settings, reportAgentId: e.target.value || null })}><option value="">Off — no room messages</option>{agents.map(a => <option key={a.id} value={a.id}>{short(a.did)}</option>)}</select></label>
      <label className="evidence-check"><input type="checkbox" checked={permanent} onChange={e => setPermanent(e.target.checked)} />I understand uploaded transcripts and supporting files become public and cannot be deleted. I will not include secrets or private information.</label>
      <label className="evidence-check"><input type="checkbox" checked={roomConsent} onChange={e => setRoomConsent(e.target.checked)} />Allow the selected enabled agent to post at most one daily summary in the PACT room, only after new archive bytes have been retrieved and checked.</label>
      <p>Free tier unavailable? Stop. Payment requested? Stop. An uncertain upload is not sent again automatically.</p><button disabled={busy}>Save controls</button><button type="button" onClick={() => setSettings(null)}>Close</button>
    </form>}
    {id && <article className="evidence-detail"><div className="evidence-detail-top"><span>RECORD / {short(id)}</span><button onClick={() => select('')}>Close ×</button></div>{!detail ? <p>Loading observed evidence…</p> : <>
      <h3>{detail.title}</h3><div className="evidence-badges"><span>{phase[detail.status] ?? detail.status}</span><span>{detail.coverage.status === 'INCOMPLETE' ? 'History incomplete' : 'No known gaps in observed window'}</span><span>{detail.assessment.payment.status === 'NO_VALUE' ? 'Rehearsal · no value' : 'Payment unverified'}</span></div>
      <dl className="evidence-facts"><div><dt>Contract / offer ID</dt><dd>{detail.id}</dd></div><div><dt>Payer DID</dt><dd>{detail.payer ?? 'Not observed'}</dd></div><div><dt>Payee DID</dt><dd>{detail.payee ?? 'Not observed'}</dd></div><div><dt>Job</dt><dd>{detail.jobId ?? 'Not specified'}</dd></div><div><dt>Terms / rail</dt><dd>{detail.assessment.state?.offer?.amount} {detail.assessment.state?.offer?.asset} · {detail.assessment.payment.rail ?? 'Not observed'}</dd></div><div><dt>Rail reference (not independently verified)</dt><dd>{detail.assessment.state?.railRef ?? 'Not observed'}</dd></div></dl>
      <p>{detail.assessment.payment.reason}</p>{detail.source.dealRoom && <a href={roomLink(detail.source.dealRoom)} target="_blank" rel="noopener noreferrer">Open derived deal room ↗</a>}
      <h4>Observed transcript</h4><p>Original signed text below. Links written inside messages are not activated. Room sequence, epoch and timestamps are venue metadata—not sender-signed fields.</p>
      {detail.records.map(r => <details className="evidence-record" key={r.id}><summary><span>{r.room} · #{r.message.seq} · epoch {r.generation ?? 'unknown'}</span><span>{r.protocolValid ? 'Signature + frame valid' : 'Signed statement / diagnostic'}</span></summary><p>Signer: {r.message.from}<br />Venue time: {r.message.ts}</p><pre>{r.message.text}</pre>{r.reason && <p>{r.reason}</p>}<a href={roomLink(r.room, r.message.seq)} target="_blank" rel="noopener noreferrer">Source message ↗ (may expire or belong to a later room epoch)</a></details>)}
      {!!detail.assessment.rejected.length && <details><summary>{detail.assessment.rejected.length} rejected transitions (did not change state)</summary><pre>{JSON.stringify(detail.assessment.rejected, null, 2)}</pre></details>}
      {!!detail.coverage.gaps.length && <details><summary>Known gaps / limits</summary><pre>{JSON.stringify(detail.coverage.gaps, null, 2)}</pre></details>}
      <div className="evidence-tools"><button disabled={busy} onClick={() => void act(async () => download(await request(`/v1/evidence/${encodeURIComponent(id)}/bundle`), `pact-evidence-${id.replace(':','-')}.json`))}>Download JSON evidence</button><button onClick={() => void act(async () => { await navigator.clipboard.writeText(`${location.origin}${location.pathname}#evidence/${id}`); setNotice('PACT record link copied. This is a live index link, not a permanent archive.'); })}>Copy record link</button>{settings?.freeUploads && <button disabled={busy} onClick={() => void act(async () => { if (!window.confirm('Permanently publish this entire transcript and all attachments? Uploaded bytes cannot be deleted. No paid fallback.')) return; const result = await request<{ status: string }>(`/v1/evidence/${encodeURIComponent(id)}/archive`, { method: 'POST', body: JSON.stringify({ confirmPermanent: true }) }, token); setNotice(`Archive: ${result.status}. This is not yet permanent-storage confirmation.`); setRevision(x => x + 1); })}>Archive free-only</button>}</div>
      <h4>Archive copies</h4>{!detail.archives.length ? <p>Not uploaded. Download the JSON now to keep your own copy.</p> : detail.archives.map(a => <div className="evidence-archive" key={a.id}><strong>{a.status.replaceAll('_', ' ')}</strong>{a.transactionId && <a href={`https://arweave.net/${a.transactionId}`} target="_blank" rel="noopener noreferrer">Open archive bytes ↗</a>}<p>{a.error ?? (a.status === 'RETRIEVABLE' ? 'Retrieved bytes match the uploaded bundle. This does not certify Arweave settlement finality.' : 'Do not treat upload acceptance as permanent-storage confirmation.')}</p></div>)}
      <h4>Supporting files</h4><p>Operator-supplied material is not a counterparty signature or proof of delivery.</p>{detail.attachments.map(a => <p key={a.sha256}>{a.label} · SHA-256 {a.sha256}</p>)}
      {settings && <label className="evidence-file">Attach public text, JSON or PDF (up to 48 KB)<input type="file" accept=".txt,.json,.pdf" disabled={busy} onChange={e => { const f = e.target.files?.[0]; e.target.value = ''; if (f) void act(async () => { if (f.size > 48000) throw new Error('Supporting file is too large.'); if (!window.confirm('Add this file to the public evidence record? Do not include confidential information.')) return; const bytes = new Uint8Array(await f.arrayBuffer()); const dataBase64 = btoa(Array.from(bytes, x => String.fromCharCode(x)).join('')); const mime = f.name.endsWith('.pdf') ? 'application/pdf' : f.name.endsWith('.json') ? 'application/json' : 'text/plain'; await request(`/v1/evidence/${encodeURIComponent(id)}/attachment`, { method: 'POST', body: JSON.stringify({ label: f.name.slice(0, 100), mime, dataBase64 }) }, token); setRevision(x => x + 1); }); }} /></label>}
      <p className="evidence-boundary">The transcript is evidence of signed statements and observed protocol transitions. It is not a judgment that work was satisfactory, a guarantee of payment, or a GenLayer ruling.</p>
    </>}</article>}
    <div className="evidence-list" aria-live="polite">{!payload && !error ? <p>Reading the evidence index…</p> : payload && !payload.cases.length ? <div className="evidence-empty"><h3>No matching evidence yet.</h3><p>{search ? 'Try a different DID, contract ID or sequence.' : 'This collector only indexes records it can observe and verify. Missing historical offers cannot be reconstructed. Choose “Deals + offers” to inspect proposals.'}</p></div> : payload?.cases.map(c => <button className={`evidence-card ${id === c.id ? 'selected' : ''}`} key={c.id} onClick={() => select(id === c.id ? '' : c.id)} aria-expanded={id === c.id}><div><small>{short(c.id)} · {new Date(c.updatedAt).toLocaleString()}</small><h3>{c.title}</h3><p>{short(c.payer)} <span aria-label="and">↔</span> {short(c.payee)}</p></div><div className="evidence-card-state"><strong>{phase[c.status] ?? c.status}</strong><span>{c.payment.status === 'NO_VALUE' ? 'Paper / memory · no value' : 'Payment not verified'}</span><span>{c.coverage === 'INCOMPLETE' ? 'Incomplete history' : 'Observed window'}</span></div><span aria-hidden="true">{id === c.id ? '−' : '+'}</span></button>)}</div>
    {payload && <><div className="evidence-pages"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 25))}>← Previous</button><span>{payload.total} matching records</span><button disabled={offset + 25 >= payload.total} onClick={() => setOffset(offset + 25)}>Next →</button></div><p className="evidence-foot">Collector {payload.collector.enabled ? 'enabled' : 'paused'} · Last board read: {payload.collector.lastSyncAt ? new Date(payload.collector.lastSyncAt).toLocaleString() : 'not yet'} · {payload.collector.count} / {payload.collector.maxRecords} stored envelopes. {payload.collector.lastError && `Last issue: ${payload.collector.lastError}`}</p></>}
  </section>;
}
